# Generated by Django 4.2.7 on 2023-12-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='user',
        ),
        migrations.AddField(
            model_name='submit',
            name='jobtitle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='jobpost.job_posts'),
            preserve_default=False,
        ),
    ]
