# Generated by Django 4.2.7 on 2023-12-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Author',
            field=models.CharField(max_length=120),
        ),
    ]
