# Generated by Django 4.2.7 on 2023-12-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0008_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
