# Generated by Django 4.2.7 on 2023-12-28 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobpost', '0011_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
